FROM node:12-alpine as build

RUN apk --no-cache add git python make g++
ENV REACT_APP_API $REACT_APP_API

WORKDIR /usr/app/

COPY frontend/package*.json ./
RUN npm install

COPY frontend/ ./

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]