FROM node:12-alpine as build

WORKDIR /usr/app/

RUN apk --no-cache --virtual build-dependencies add \
  git \
  python \
  make \
  g++ \
  && npm i \
  && apk del build-dependencies

COPY backend/package*.json ./

COPY backend/ ./

RUN npm install
RUN npm run build

EXPOSE 5000

ENV NODE_ENV=development

CMD ["node", "--unhandled-rejections=strict", "-r", "source-map-support/register", "build/index.js"]
